plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.todokanai.composepracticenew.domain'
    compileSdk 34
    defaultConfig { minSdk 30 }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlin { jvmToolchain(17) }
}

dependencies {
    implementation 'net.lingala.zip4j:zip4j:2.7.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'
}
